# log detail level
# 0 — silent
# 1 — only errors about listening ports
# 2 — errors of creating new connections
# 3 — log every connect and disconnect
verbose: 2
redirects:
  - src: :8080
    dst: ya.r:80
  - src: :8081
    dst: 127.0.0.1:8384
